name: ds
channels:
  - conda-forge
  - defaults
dependencies:
  - autopep8>=2.3.2
  - babel>=2.16.0
  - beautifulsoup4>=4.12.3
  - black>=24.10.0
  - click>=8.1.8
  - ipykernel>=6.29.5
  - ipython>=8.31.0
  - ipython_genutils>=0.2.0
  - ipywidgets>=8.1.5
  - isoduration>=20.11.0
  - isort>=5.13.2
  - jupyter>=1.1.1
  - jupyter-lsp>=2.2.5
  - jupyter_client>=8.6.3
  - jupyter_console>=6.6.3
  - jupyter_core>=5.7.2
  - jupyter_events>=0.11.0
  - jupyter_server>=2.15.0
  - jupyter_server_terminals>=0.5.3
  - jupyterlab>=4.3.4
  - jupyterlab_pygments>=0.3.0
  - jupyterlab_server>=2.27.3
  - jupyterlab_widgets>=3.0.13
  - matplotlib>=3.9.2
  - mypy_extensions>=1.0.0
  - mysql-common>=8.0.33
  - mysql-libs>=8.0.33
  - nbclassic>=1.2.0
  - nbclient>=0.10.2
  - nbconvert>=7.16.5
  - nbconvert-core>=7.16.5
  - nbconvert-pandoc>=7.16.5
  - nbformat>=5.10.4
  - ncurses>=6.5
  - notebook>=7.3.2
  - notebook-shim>=0.2.4
  - numpy>=1.26.4
  - openjpeg>=2.5.0
  - openpyxl>=3.1.5
  - openssl>=3.4.0
  - overrides>=7.7.0
  - pandas>=2.2.3
  - pandoc>=3.6.2
  - pandocfilters>=1.5.0
  - pathspec>=0.12.1
  - pickleshare>=0.7.5
  - pillow>=9.4.0
  - pip>=24.3.1
  - plotly>=5.24.1
  - ptyprocess>=0.7.0
  - pure_eval>=0.2.3
  - pycodestyle>=2.12.1
  - pycparser>=2.22
  - pygments>=2.19.1
  - pylint>=3.3.3
  - pyopenssl>=25.0.0
  - pyparsing>=3.2.1
  - pysocks>=1.7.1
  - python>=3.12
  - python-dateutil>=2.9.0
  - python-fastjsonschema>=2.21.1
  - python-json-logger>=2.0.7
  - python-slugify>=8.0.4
  - python-tzdata>=2024.2
  - pytz>=2024.1
  - pyyaml>=6.0.2
  - pyzmq>=26.2.0
  - qhull>=2020.2
  - qt>=5.12.9
  - qtconsole>=5.6.1
  - qtconsole-base>=5.6.1
  - qtpy>=2.4.2
  - readline>=8.2
  - referencing>=0.36.1
  - requests>=2.32.3
  - scikit-learn>=1.5.2
  - scipy>=1.11.1
  - seaborn>=0.13.2
  - seaborn-base>=0.13.2
  - setuptools>=75.8.0
  - sqlite>=3.48.0
  - stack_data>=0.6.3
  - statsmodels>=0.14.4
  - testpath>=0.6.0
  - text-unidecode>=1.3
  - threadpoolctl>=3.5.0
  - tinycss2>=1.4.0
  - tk>=8.6.13
  - toml>=0.10.2
  - tomli>=2.2.1
  - tomlkit>=0.13.2
  - tornado>=6.4.2
  - tqdm>=4.67.1
  - traitlets>=5.14.3
  - types-python-dateutil>=2.9.0
  - typing-extensions>=4.12.2
  - typing_extensions>=4.12.2
  - typing_utils>=0.1.0
  - tzdata>=2025a
  - unicodedata2>=16.0.0
  - unidecode>=1.3.8
  - urllib3>=2.3.0
  - wcwidth>=0.2.13
  - wheel>=0.45.1
  - widgetsnbextension>=4.0.13
  - yaml>=0.2.5
  - yarl>=1.18.3